require 'modules.oop-new.objects.compiletime'
require 'modules.oop-new.objects.WarObject'
require 'modules.oop-new.objects.WarObjects'
require 'modules.oop-new.objects.WarMapObjects'
require 'modules.oop-new.objects.WarMap'