require 'modules.oop-new.fields.camera.camera field'
require 'modules.oop-new.fields.camera.blend mode'
require 'modules.oop-new.fields.camera.rarity control'
require 'modules.oop-new.fields.camera.tex map flags'
require 'modules.oop-new.fields.camera.fog state'
require 'modules.oop-new.fields.camera.camera margin'